USE [master]
GO

/****** Object:  Database [ALPI]    Script Date: 19/02/2020 15:32:04 ******/
CREATE DATABASE [ALPI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ALPI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ALPI.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ALPI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\ALPI_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ALPI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ALPI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ALPI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ALPI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ALPI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ALPI] SET ARITHABORT OFF 
GO

ALTER DATABASE [ALPI] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ALPI] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ALPI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ALPI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ALPI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ALPI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ALPI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ALPI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ALPI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ALPI] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ALPI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ALPI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ALPI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ALPI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ALPI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ALPI] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ALPI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ALPI] SET RECOVERY FULL 
GO

ALTER DATABASE [ALPI] SET  MULTI_USER 
GO

ALTER DATABASE [ALPI] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ALPI] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ALPI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ALPI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ALPI] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ALPI] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ALPI] SET  READ_WRITE 
GO

USE ALPI;

CREATE TABLE tab_people(id INT IDENTITY PRIMARY KEY, nome VARCHAR(MAX) , cep VARCHAR(MAX) , logradouro VARCHAR(MAX) , numeros VARCHAR(MAX), complemento VARCHAR(MAX), nascimento DATE, genero VARCHAR(MAX));
GO

INSERT INTO tab_people(nome , cep , logradouro , numeros , complemento , nascimento , genero) VALUES ('teste', '0000-000' , 'teste' , 'teste', 'teste' , '2020-02-19' , 'teste');
GO

SELECT * FROM tab_people;
GO